# AI-CodeReview Docker Compose 配置 (单容器模式)
# 在一个容器中运行所有服务：API、UI、后台任务

services:
  # AI 代码审查应用服务 (包含所有功能)
  ai-codereview:
    build:
      context: .
      dockerfile: Dockerfile
      target: app
    image: ghcr.io/zhao-zg/ai-codereview:latest
    container_name: ai-codereview
    restart: unless-stopped
    
    # 端口映射
    ports:
      - "5001:5001"    # Flask API 端口
      - "5002:5002"    # Streamlit UI 端口
    
    # 卷映射 - 关键配置
    volumes:
      # 配置目录映射（自动复制配置文件）
      - ./conf:/app/conf
      
      # 数据目录映射（持久化数据）
      - ./data:/app/data
      - ./log:/app/log
      
      # SVN 工作目录映射
      - ./data/svn:/app/data/svn
    
    # 环境变量配置
    environment:
      # 运行模式 - 使用统一模式
      - DOCKER_RUN_MODE=all
      
      # 基础配置
      - TZ=Asia/Shanghai
      - LOG_LEVEL=INFO
      - PYTHON_ENV=production
      
      # 后台任务配置
      - ENABLE_WORKER=true
      - QUEUE_DRIVER=process
      
      # LLM 服务配置
      - LLM_PROVIDER=${LLM_PROVIDER:-}
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY:-}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}      
      # SVN 配置
      - SVN_CHECK_ENABLED=false
      - SVN_CHECK_INTERVAL=300
      
      # Redis 配置（如果使用 RQ 队列）
      - REDIS_URL=redis://redis:6379/0
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    
    # 健康检查
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5001/health || wget --no-verbose --tries=1 --spider http://localhost:5001/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    
    # 网络配置
    networks:
      - ai-codereview-network

  # Redis 服务（可选，仅在使用 RQ 队列时需要）
  redis:
    image: redis:7-alpine
    container_name: ai-codereview-redis
    restart: unless-stopped
    
    # Redis 配置
    command: >
      redis-server
      --appendonly yes
      --maxmemory 256m
      --maxmemory-policy allkeys-lru
    
    # 数据持久化
    volumes:
      - redis_data:/data
    
    # 健康检查
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 15s
      timeout: 5s
      retries: 3
    
    # 网络配置
    networks:
      - ai-codereview-network
    
    # 仅在使用 RQ 队列时启用
    profiles:
      - redis

# 定义数据卷
volumes:
  # Redis 数据卷
  redis_data:
    driver: local

# 网络配置
networks:
  ai-codereview-network:
    name: ai-codereview-network
    driver: bridge
    ipam:
      config:
        - subnet: 172.29.0.0/16
