services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: app
    image: ghcr.io/zhao-zg/ai-codereview-gitlab:latest
    ports:
      - "5001:5001"
      - "5002:5002"
    volumes:
      - ./data:/app/data
      - ./log:/app/log
      - ./data/svn:/app/data/svn
      - ./conf:/app/conf
    environment:
      # 基础配置 - 如果.env文件存在会被覆盖
      - TZ=Asia/Shanghai
      - SERVER_PORT=5001
      - LLM_PROVIDER=deepseek
      - LOG_LEVEL=INFO
      - DASHBOARD_USERNAME=admin
      - DASHBOARD_PASSWORD=admin123
      - VERSION_TRACKING_ENABLED=1
      - REUSE_PREVIOUS_REVIEW_RESULT=1
      - VERSION_TRACKING_RETENTION_DAYS=30
      - REVIEW_STYLE=professional
      # 通知配置默认关闭
      - WX_WORK_ENABLED=0
      - DINGTALK_ENABLED=0
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
