name: Basic Syntax Check

on:
  push:
    branches: [ "main", "master", "develop" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  syntax-check:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Python syntax check
      run: |
        # Basic syntax check
        python -m py_compile api.py
        python -m py_compile ui.py
        python -m py_compile quick_start.py
        echo "Basic syntax check passed"

    - name: Requirements check
      run: |
        # Check if requirements.txt is valid
        pip install --dry-run -r requirements.txt
        echo "Requirements file check passed"
