name: Basic Syntax Check

on:
  push:
    branches: [ "main", "master", "develop" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  syntax-check:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Python syntax check
      run: |
        # 基本语法检查
        python -m py_compile api.py
        python -m py_compile ui.py
        python -m py_compile quick_start.py
        echo "✅ 主要文件语法检查通过"

    - name: Requirements check
      run: |
        # 检查requirements.txt是否有效
        pip install --dry-run -r requirements.txt
        echo "✅ 依赖文件格式检查通过"
